### PR TITLE
Update stores info

### PR DESCRIPTION
**Pull request by licaon-kter**
...and put it where users want it ;)

### CODE REVIEW

**Comment by juha-h** [comment]
Main purpose of README.md is to describe how the application can be build from the source.  It also includes pointers that tell where the application can be downloaded if reader does not want to roll his/her own.  That information does not (in my opinion) belong to the beginning of the text.

**Comment by licaon-kter** [comment]
At least fix the Google icon, put them on the same row and such.

You realise you'll have more users than capablu devs visiting here right? (Well IMHO ;))

**Comment by juha-h** [comment]
Licaon_Kter writes:

> At least fix the Google icon, put them on the same row and such.

I removed the images altogether, since I could not immediately figure
out how to get them the same size and centered.  Better use time for
something else.

**Comment by licaon-kter** [comment]
My PR was for the same size, no idea about center though. :)

**Pull request closed without merging**
